name: Develop CI/CD

on:
  push:
    branches: [ "develop" ]

env:
  ARTIFACT_TAG: "dev"
jobs:
  build:
    name: Build assets
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set version
      id: config
      run: |
        APP_VERSION=$(cat package.json | jq -r '.version')
        BUILD_VERSION="${APP_VERSION}-${{ env.ARTIFACT_TAG }}.${{ github.run_number }}"
        ARTIFACT="${{ github.event.repository.name }}-${BUILD_VERSION}"
        echo "APP_VERSION=$(echo $APP_VERSION)" >> $GITHUB_ENV
        echo "BUILD_VERSION=$(echo $BUILD_VERSION)" >> $GITHUB_ENV
        echo "ARTIFACT=$(echo $ARTIFACT)" >> $GITHUB_ENV

    - uses: actions/setup-node@v3
      name: Setup NodeJs
      with:
        node-version: 16.x
        cache: 'npm'

    - name: Build assets
      run: |
        npm ci
        npm run build

    - name: Create version file
      run: |
        cat <<- CONFIG > dist/version.json
        {
          "app_version": "${{ env.APP_VERSION }}",
          "build_version": "${{ env.BUILD_VERSION }}"
        };
        CONFIG

    - name: Create dist archive
      run: |
        ls -alp dist/
        cat dist/version.json
        tar -zcvf ${{ env.ARTIFACT }}.tar.gz dist

    - name: Upload dist artifact
      uses: kittaakos/upload-artifact-as-is@v0
      with:
        path: ${{ env.ARTIFACT }}.tar.gz
