# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Develop CI/CD

on:
#  release:
#    types:
#      - prereleased
  push:
    branches: [ "develop" ]
#  pull_request:
#    branches: [ "develop" ]

env:
  ARTIFACT_TAG: "dev"
jobs:
  build:
    name: Build assets
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: set app version
      id: config
      run: |
        APP_VERSION=$(cat package.json | jq -r '.version')
        BUILD_VERSION="${APP_VERSION}-${{ env.ARTIFACT_TAG }}.${{ github.run_number }}"
        echo "APP_VERSION=$(echo $APP_VERSION)" >> $GITHUB_ENV
        echo "BUILD_VERSION=$(echo $BUILD_VERSION)" >> $GITHUB_ENV

    - name: show app version
      run: |
        echo "APP_VERSION: ${{ env.APP_VERSION }}"
        echo "BUILD_VERSION: ${{ env.BUILD_VERSION }}"

    - uses: actions/setup-node@v3
      name: Setup NodeJs
      with:
        node-version: 16.x
        cache: 'npm'

    - run: npm ci

#    - name: Print GitHub event action
#      run: |
#        echo "author = ${{ github.event.head_commit.author.name }}"
#        echo "github.event_name = ${{ github.event_name }}"
#        echo "github.event_path = ${{ github.event_path }}"
#        cat ${{ github.event_path }} | jq


#    - name: Use Node.js ${{ matrix.node-version }}
#      uses: actions/setup-node@v3
#      with:
##        node-version: ${{ matrix.node-version }}
#        node-version: 16.x
#        cache: 'npm'

#    - run: npm ci
#    - run: npm run build --if-present
#    - run: npm test
